/* =========== AUTH USER ACTION TYPES =========== */
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_PENDING = "AUTH_USER_PENDING";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";

/* =========== LOAD USER ACTION TYPES =========== */
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_PENDING = "LOAD_USER_PENDING";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

/* =========== LOAD TWISTS ACTION TYPES =========== */
export const LOAD_TWISTS_SUCCESS = "LOAD_TWISTS_SUCCESS";
export const LOAD_TWISTS_PENDING = "LOAD_TWISTS_PENDING";
export const LOAD_TWISTS_ERROR = "LOAD_TWISTS_ERROR";

/* =========== LOAD OWN TWISTS ACTION TYPES =========== */
export const LOAD_OWN_TWISTS_SUCCESS = "LOAD_OWN_TWISTS_SUCCESS";
export const LOAD_OWN_TWISTS_PENDING = "LOAD_OWN_TWISTS_PENDING";
export const LOAD_OWN_TWISTS_ERROR = "LOAD_OWN_TWISTS_ERROR";

/* =========== LOAD TWISTER ACTION TYPES =========== */
export const LOAD_TWISTER_SUCCESS = "LOAD_TWISTER_SUCCESS";
export const LOAD_TWISTER_PENDING = "LOAD_TWISTER_PENDING";
export const LOAD_TWISTER_ERROR = "LOAD_TWISTER_ERROR";

/* =========== LOAD TWISTER TWISTS ACTION TYPES =========== */
export const LOAD_TWISTER_TWISTS_SUCCESS = "LOAD_TWISTER_TWISTS_SUCCESS";
export const LOAD_TWISTER_TWISTS_ERROR = "LOAD_TWISTER_TWISTS_ERROR";

/* =========== LIKE or UNLIKE TWIST ACTION TYPES =========== */
export const LIKE_ONE_TWIST_SUCCESS = "LIKE_ONE_TWIST_SUCCESS";
export const LIKE_ONE_TWIST_ERROR = "LIKE_ONE_TWIST_ERROR";

/* =========== LIKE or UNLIKE TWIST ACTION TYPES =========== */
export const UNLIKE_ONE_TWIST_SUCCESS = "UNLIKE_ONE_TWIST_SUCCESS";
export const UNLIKE_ONE_TWIST_ERROR = "UNLIKE_ONE_TWIST_ERROR";

/* =========== FOLLOW TWISTER ACTION TYPES =========== */
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_ERROR = "FOLLOW_ERROR";

/* =========== UNFOLLOW TWISTER ACTION TYPES =========== */
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_ERROR = "UNFOLLOW_ERROR";
